#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

year=$1

function check_answer {
  answer_file=$1
  output_file=$2
  if ! diff_output=$(git diff --no-ext-diff --color --no-index --ignore-all-space --ignore-blank-lines $answer_file $output_file); then
    echo >&2
    echo >&2 'The answer was incorrect.'
    echo >&2 $diff_output
    return 1
  fi
}

output_file=$(mktemp)
trap 'rm -f $output_file' EXIT

for day in {1..24}; do
  day=$(printf '%02d' $day)
  input_file="${year}/AOC_${day}.input"
  for part in {1..2}; do
    answer_file="${year}/AOC_${day}_${part}.answer"
    if [[ -e $answer_file ]]; then
      echo >&2 "\nRunning year ${year}, day ${day}, part ${part}..."
      < $input_file ./${year}/run $day $part | tee $output_file
      check_answer $answer_file $output_file
    fi
  done
done

input_file="${year}/AOC_25.input"
answer_file="${year}/AOC_25.answer"
if [[ -e $answer_file ]]; then
  echo >&2 "\nRunning year ${year}, day 25..."
  < $input_file ./${year}/run 25 | tee $output_file
  check_answer $answer_file $output_file
fi
