#!/usr/bin/env zsh

set -e

cd $(dirname $0)

if [[ ! ( $1 =~ '^[0-9]+$' ) ]]; then
  echo >&2 "Usage: $0 <day>"
  exit 2
fi

TIMEFMT=$'\n%U user %S system %P cpu %*E total'

day=$(printf '%02d' $1)
executable=./exe

program="AOC_${day}.hs"
input="AOC_${day}.input"

if [[ ! -e $program ]]; then
  echo "${program} does not exist."
  exit 1
fi

stack ghc -- -O2 -o $executable $program

if [[ -t 0 ]]; then
  if [[ ! -e $input ]]; then
    echo "${input} does not exist."
    exit 1
  fi

  time $executable $program < $input
else
  time $executable $program
fi
