#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

if [[ $# -ne 1 ]]; then
  echo >&2 "Usage: $0 YEAR"
  exit
fi

year=$1
shell_file="${year}/shell.nix"

if [[ ! -e $shell_file ]]; then
  echo >&2 "Invalid year: ${year}"
  exit 1
fi

nix-shell --command "$SHELL" "$(dirname $0)/${shell_file}"
