[package]
name = "advent-of-code-2019"
version = "1.0.0"
authors = ["Samir Talwar <samir@noodlesandwich.com>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
num = "0.2.1"
pancurses = "0.16"
permutohedron = "0.2.4"
