#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

cd $(dirname $0)

optimize=false
while [[ $1 =~ ^- ]]; do
  case $1 in
    -O)
      optimize=true
      shift
      ;;
  esac
done

day=$(printf '%02d' $1)
shift
if [[ $# -gt 0 ]]; then
  part=${1:-}
  shift
fi

output_directory="${PWD}/build"
if (( ${+part} )); then
  name="AOC_${day}_${part}"
  executable_name="aoc_${day}_${part}"
else
  name="AOC_${day}"
  executable_name="aoc_${day}"
fi

mkdir -p $output_directory

file="${name}.rs"
if $optimize; then
  executable="${output_directory}/release/${executable_name}"
  compilation_args=('--release')
else
  executable="${output_directory}/debug/${executable_name}"
  compilation_args=()
  export RUST_BACKTRACE=1
fi
cargo_file="Cargo.toml"
cp -f "Cargo.template.toml" $cargo_file
for bin in AOC_*.rs; do
  echo >> $cargo_file
  echo '[[bin]]' >> $cargo_file
  echo "name = \"$(basename $bin .rs | sed "s/^AOC_/aoc_/")\"" >> $cargo_file
  echo "path = \"$(basename $bin)\"" >> $cargo_file
done

cargo fmt
cargo build $compilation_args --target-dir $output_directory --bin $executable_name
echo >&2

time $executable $@
