#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

cd $(dirname $0)

while [[ $1 =~ ^- ]]; do
  case $1 in
    -O)
      # ignore
      shift
      ;;
  esac
done

day=$(printf '%02d' $1)
shift
if [[ $# -gt 0 ]]; then
  part=${1:-}
  shift
fi

name="AOC_${day}_${part}"
db_name="aoc_${day}_${part}"

file="${name}.sql"
if [[ ! -e $file ]]; then
  echo >&2 "${file} does not exist."
  exit 2
fi

psql=(docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U postgres)

# start PostgreSQL
docker compose up --detach --wait
# recreate the database
$psql -q <<< "DROP DATABASE IF EXISTS ${db_name}; CREATE DATABASE ${db_name};" || {
  # if that fails, drop everything and try again
  docker compose down --volumes
  docker compose up --detach --wait
  $psql -q <<< "CREATE DATABASE ${db_name};"
}

# write the input to a file inside the container
docker compose exec -T postgres bash -c 'cat > /tmp/input'

command=($psql $db_name -v input=/tmp/input -f "/src/${file}" -o /dev/stderr)
time $command
